image: docker:git

variables:
    PACKAGES: >
        ruvu_carrot_local_planner
        turtlebot3_carrot_planner
    IMAGE_PATH: registry.gitlab.com/$CI_PROJECT_PATH

before_script:
    - mkdir ~/.ssh
    - ssh-keyscan -t rsa gitlab.com > ~/.ssh/known_hosts
    - echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa

    # Clone the ruvu-env for the docker images
    - git clone git@gitlab.com:ruvu/environment.git ~/.ruvu
    - cd ~/.ruvu

    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

stages:
    - build
    - test
    - release

.build-on-schedule:
    stage: build
    only:
        - schedules
    script:
        - docker build --pull --build-arg SSH_PRIVATE_KEY="$SSH_PRIVATE_KEY" --build-arg BASE_IMAGE="ros:$ROS_DISTRO-ros-base" --build-arg WORKSPACE=common --build-arg PACKAGES="$PACKAGES" --build-arg VERSION="$CI_COMMIT_REF_NAME" -t $IMAGE_PATH/$ROS_DISTRO:${CI_COMMIT_REF_NAME//\//-} -f docker/Dockerfile .
        - docker push $IMAGE_PATH/$ROS_DISTRO:${CI_COMMIT_REF_NAME//\//-}

.build:
    stage: build
    except:
        - schedules
    script:
        - docker build --pull --build-arg SSH_PRIVATE_KEY="$SSH_PRIVATE_KEY" --build-arg BASE_IMAGE="${IMAGE_PATH}/$ROS_DISTRO:latest" --build-arg WORKSPACE=common --build-arg PACKAGES="$PACKAGES" --build-arg VERSION="$CI_COMMIT_REF_NAME" -t $IMAGE_PATH/$ROS_DISTRO:${CI_COMMIT_REF_NAME//\//-} -f docker/Dockerfile .
        - docker push $IMAGE_PATH/$ROS_DISTRO:${CI_COMMIT_REF_NAME//\//-}

.test:
    stage: test
    script:
        - docker pull $IMAGE_PATH/$ROS_DISTRO:${CI_COMMIT_REF_NAME//\//-}
        - docker run --rm --entrypoint /.ruvu/docker/entrypoint_run_tests.sh $IMAGE_PATH/$ROS_DISTRO:${CI_COMMIT_REF_NAME//\//-} catkin_test_results

.release:
    stage: release
    only:
        refs:
          - master
    script:
        - docker pull $IMAGE_PATH/$ROS_DISTRO:${CI_COMMIT_REF_NAME//\//-}
        - docker tag $IMAGE_PATH/$ROS_DISTRO:${CI_COMMIT_REF_NAME//\//-} $IMAGE_PATH/$ROS_DISTRO:latest
        - docker push $IMAGE_PATH/$ROS_DISTRO:latest

indigo-build-on-schedule:
  extends: .build-on-schedule
  variables:
    ROS_DISTRO: indigo
    # turtlebot3 stack is not released for indigo
    PACKAGES: >
      ruvu_carrot_local_planner
indigo-build:
  extends: .build
  variables:
    ROS_DISTRO: indigo
    # turtlebot3 stack is not released for indigo
    PACKAGES: >
      ruvu_carrot_local_planner
indigo-test:
  extends: .test
  variables:
    ROS_DISTRO: indigo
indigo-release:
  extends: .release
  variables:
    ROS_DISTRO: indigo

kinetic-build-on-schedule:
  extends: .build-on-schedule
  variables:
    ROS_DISTRO: kinetic
kinetic-build:
  extends: .build
  variables:
    ROS_DISTRO: kinetic
kinetic-test:
  extends: .test
  variables:
    ROS_DISTRO: kinetic
kinetic-release:
  extends: .release
  variables:
    ROS_DISTRO: kinetic

melodic-build-on-schedule:
  extends: .build-on-schedule
  variables:
    ROS_DISTRO: melodic
melodic-build:
  extends: .build
  variables:
    ROS_DISTRO: melodic
melodic-test:
  extends: .test
  variables:
    ROS_DISTRO: melodic
melodic-release:
  extends: .release
  variables:
    ROS_DISTRO: melodic
