---
include:
  - project: ruvu/environment
    file: ROS.gitlab-ci.yml

variables:
  WORKSPACE: common
  PACKAGES: >
    ruvu_carrot_local_planner
    turtlebot3_carrot_planner

melodic-build-on-schedule:
  extends: .build-on-schedule
  variables:
    ROS_DISTRO: melodic
melodic-build:
  extends: .build
  variables:
    ROS_DISTRO: melodic
melodic-test:
  extends: .test
  variables:
    ROS_DISTRO: melodic
melodic-release:
  extends: .release
  variables:
    ROS_DISTRO: melodic

noetic-build-on-schedule:
  extends: .build-on-schedule
  variables:
    ROS_DISTRO: noetic
    PACKAGES: >
      ruvu_carrot_local_planner
noetic-build:
  extends: .build
  variables:
    ROS_DISTRO: noetic
    PACKAGES: >
      ruvu_carrot_local_planner
noetic-test:
  extends: .test
  variables:
    ROS_DISTRO: noetic
noetic-release:
  extends: .release
  variables:
    ROS_DISTRO: noetic
